#!/bin/csh -fx

# run a tokenized basic program in C64 mode
# usage: run_prg <tokenized basic program> [-eb/-bb] [/dev/ttyUSBx]

unset echo # disable command echoing

if ( $#argv < 1 ) then
  echo "Usage: run_prg <tokenized basic program> [-eb/-bb] [/dev/ttyUSBx]"
  echo "Please provide at least one argument!"
  exit
endif

set coredir=~/dev/mega65-core

set bitfile=${coredir}/bin/nexys4ddr.bit
set kickupfile=${coredir}/bin/KICKUP.M65
set romfile=${coredir}/bin/MEGA65.ROM
#set charromfile=${coredir}/bin/CHARROM.ROM
set charromfile=bin/asciifont.bin

set megabasic=bin/megabasic64.prg

set port=/dev/ttyUSB1
if ( $#argv == 3 ) then
  set port=$3
endif

if ( $#argv >= 2 && "$2" == "-eb" ) then
  echo "Running $1, with extended basic"
  make ${megabasic} && \
  m65 -l ${port} -b ${bitfile} -k ${kickupfile} -R ${romfile} -C ${charromfile} -4 -r ${megabasic} && \
  m65 -l ${port} -4 -r $1
else if ( $#argv >= 2 && "$2" == "-bb" ) then
  echo "Running $1, without extended basic"
  m65 -l ${port} -b ${bitfile} -k ${kickupfile} -R ${romfile} -C ${charromfile} -4 -r $1
else
  echo "Running $1, without extended basic"
  m65 -l ${port} -b ${bitfile} -k ${kickupfile} -R ${romfile} -C ${charromfile} -4 -r $1
endif
