#!/bin/csh -fx

# make and run the telephony software
# usage: run_telephony [/dev/ttyUSBx]

if ( -e mega65.cfg ) then
  set coredir=`cat mega65.cfg | grep coredir | cut -f2 -d=`
  echo "Setting coredir to $coredir from mega65.cfg"
else
  echo "Setting coredir to default. Add coredir=... to mega65.cfg to override"
  set coredir=~/dev/mega65-core
endif

set bitfile=${coredir}/bin/nexys4ddr.bit
set kickupfile=${coredir}/bin/KICKUP.M65
set romfile=${coredir}/bin/MEGA65.ROM
set charromfile=bin/asciifont.bin

set megabasic=bin/megabasic64.prg
set telephony=bin/telephony.prg

set port=/dev/ttyUSB1
if ( x$1 != x ) then
  set port=$1
endif

make ${megabasic} ${telephony} ${charromfile} && \
m65 -E -l ${port} -b ${bitfile} -k ${kickupfile} -R ${romfile} -C ${charromfile} -4 -r ${megabasic}  && \
 m65 -E -l ${port} -4 -r ${telephony}
