#!/bin/csh -fx

# usage: testbas <basic program as ASCII> [/dev/ttyUSBx]

#set bitfile=~/dev/mega65-core/bin/nexys4-ec4b67b.bit
#set bitfile=~/dev/mega65-core/bin/nexys4-2c60aef.bit

set coredir=~/Projects/mega65/mega65-core
set bitfile=${coredir}/bin/lcd4ddr.bit

set port=/dev/ttyUSB1
if ( x$2 != x ) then
  set port=$2
endif
echo "arg1 = $1"
make bin/megabasic64.prg && \
m65 -l ${port} -b ${bitfile} -k ${coredir}/bin/KICKUP.M65 -R ${coredir}/bin/MEGA65.ROM -C ${coredir}/bin/CHARROM.ROM -4 -r bin/megabasic64.prg && \
m65 -l ${port} -4 -r $1
