#!/bin/csh -f

# test the extended basic (run in C64 mode)
# usage: test_eb [/dev/ttyUSBx]

set coredir=~/dev/mega65-core

set bitfile=${coredir}/bin/lcd4ddr.bit
set kickupfile=${coredir}/bin/KICKUP.M65
set romfile=${coredir}/bin/MEGA65.ROM
set charromfile=${coredir}/bin/CHARROM.ROM

set megabasic=bin/megabasic64.prg

set port=/dev/ttyUSB1
if ( x$1 != x ) then
  set port=$1
endif

make ${megabasic} && \
m65 -l ${port} -b ${bitfile} -k ${kickupfile} -R ${romfile} -C ${charromfile} -4 -r ${megabasic} && \
m65dbg -d ${port}
